galaxy_info:
  author: Aleem Ladha
  description: Role for installing and configuring Wazuh Manager
  license: MIT
  min_ansible_version: 2.10
  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
    - name: CentOS
      versions:
        - 7
        - 8
    - name: Debian
      versions:
        - kali-rolling
  galaxy_tags:
    - wazuh
    - security
    - monitoring
